### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/devcontainer-features#19]
![image](https://user-images.githubusercontent.com/61068799/235573781-995a3444-98c3-44c0-b4ef-7939db88be39.png)

@jcbhmr clean up your own mess lmao 🤣

**Comment by jcbhmr** [comment]
[jcbhmr-features](https://github.com/devcontainers-community/features/tree/jcbhmr-features) is an old version of my @jcbhmr/devcontainer-features repo just hosted here for easier swap-age between the two. that stays for a bit. it has two features: `llvm` and `cmake` https://github.com/devcontainers-community/features/tree/jcbhmr-features/src

_more updates forthcoming_

**Comment by jcbhmr** [comment]
ive deleted the add-llvm and add-cmake branches since they are just re-implementations of the thing from `jcbhmr-features`, but re-based against `main`.

ive deleted the `add-tooling` branch since we can wait for the official version of shared code files (and it also was based on `jcbhmr-features`):
https://github.com/devcontainers/spec/issues/129 (proposal doc pr is merged! 🎉 https://github.com/devcontainers/spec/pull/209)
_no devcontainers/cli issue yet 🤔_

**Comment by jcbhmr** [comment]
_for future reference of @jcbhmr to quick hover to see status at-a-glance_

core sharing include:
https://github.com/devcontainers/spec/issues/129
https://github.com/devcontainers/spec/pull/209
_no proto yet_

composable dependsOn:
https://github.com/devcontainers/spec/issues/109
https://github.com/devcontainers/spec/pull/234
https://github.com/devcontainers/cli/pull/511

**Comment by jcbhmr** [comment]
from codespace-jcbhmr-... the only parts worth salvaging are the readme and the gitattributes

readme is attached: 
[README.md](https://github.com/devcontainers-community/features/files/11369628/README.md)

the .gitattributes is quite small but a good idea to add!
```sh
# On Windows, we want Bash scripts to have the right line endings so that the
# hash-bang headers work right when executing a Windows-realm *.sh file from a
# WSL terminal.
*.sh text eol=lf
```

**Comment by jcbhmr** [comment]
outline-scope is at +1 commit beyond main-OLD. that means byebye main-OLD.

**Comment by jcbhmr** [comment]
from outline-scope, the only real parts worth saving are

- bash_modules bash libs [bash_modules.zip](https://github.com/devcontainers-community/features/files/11369651/bash_modules.zip)
- a beginning FAQ wiki doc [FAQ.md](https://github.com/devcontainers-community/features/files/11369650/FAQ.md)
- and a beginner deno feature with A LOT OF DOCS like A LOT of comments [deno.zip](https://github.com/devcontainers-community/features/files/11369653/deno.zip) (ref #18 )

**Comment by jcbhmr** [comment]
looks pretty good!
![image](https://user-images.githubusercontent.com/61068799/235579365-3588c95e-29df-4131-a43e-1f3705f0b3ff.png)

**Comment by nanis94** [comment]
master

**Comment by nanis94** [comment]
#19 master

**Comment by nanis94** [comment]
sayfa #19 master

**Comment by nanis94** [comment]
sayfa #19 main
