### ISSUE TITLE
Get pages static build working

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/devcontainer-features#4]
```sh
@jcbhmr ➜ /workspaces/devcontainer-features/docs (main) $ npm run prepack

> @jcbhmr/devcontainer-features~docs@0.1.0 prepack
> next build && next export

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Linting and checking validity of types  
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Route (app)                                Size     First Load JS
─ ○ /                                      137 B          67.5 kB
+ First Load JS shared by all              67.3 kB
  ├ chunks/701-3d0e1b64b039764a.js         65.5 kB
  ├ chunks/main-app-abe896845ef83255.js    202 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   179 B          90.3 kB
+ First Load JS shared by all              90.2 kB
  ├ chunks/main-9ceee7cc7e73f31b.js        88.4 kB
  ├ chunks/pages/_app-4dbef4ff05023091.js  193 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - using build directory: /workspaces/devcontainer-features/docs/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/workspaces/devcontainer-features/docs/next.config.js". Generating map from "./pages"
info  - Launching 1 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (/workspaces/devcontainer-features/docs/node_modules/next/dist/server/require.js:77:15)
    at /workspaces/devcontainer-features/docs/node_modules/next/dist/export/index.js:392:48
    at Array.map (<anonymous>)
    at /workspaces/devcontainer-features/docs/node_modules/next/dist/export/index.js:383:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/workspaces/devcontainer-features/docs/node_modules/next/dist/trace/trace.js:79:20) {
  code: 'ENOENT'
}
```

**Comment by jcbhmr** [comment]
Sidenote: consider using https://vercel.com/templates/next.js/documentation-starter-kit

**Comment by jcbhmr** [comment]
Sidenote: consider using https://vercel.com/templates/next.js/documentation-starter-kit

**Comment by jcbhmr** [comment]
Also note that maybe we should NOT use the app dir experimental feature and maybe that would solve things?

**Comment by jcbhmr** [comment]
Then again, maybe I just need to add this https://nextjs.org/docs/advanced-features/static-html-export

```js
/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  output: 'export',
}

module.exports = nextConfig
```

**Comment by jcbhmr** [comment]
[Supported Features](https://nextjs.org/docs/advanced-features/static-html-export#supported-features)
-----------------------------------------------------------------------------------------------------

The majority of core Next.js features needed to build a static site are supported, including:

-   [Dynamic Routes when using `getStaticPaths`](https://nextjs.org/docs/routing/dynamic-routes)
-   Prefetching with `next/link`
-   Preloading JavaScript
-   [Dynamic Imports](https://nextjs.org/docs/advanced-features/dynamic-import)
-   Any styling options (e.g. CSS Modules, styled-jsx)
-   [Client-side data fetching](https://nextjs.org/docs/basic-features/data-fetching/client-side)
-   [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching/get-static-props)
-   [`getStaticPaths`](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths)
-   [Image Optimization](https://nextjs.org/docs/basic-features/image-optimization) using a [custom loader](https://nextjs.org/docs/basic-features/image-optimization#loaders)

[Unsupported Features](https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features)
---------------------------------------------------------------------------------------------------------

Features that require a Node.js server, or dynamic logic that cannot be computed during the build process, are not supported:

-   [Image Optimization](https://nextjs.org/docs/basic-features/image-optimization) (default loader)
-   [Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing)
-   [API Routes](https://nextjs.org/docs/api-routes/introduction)
-   [Rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites)
-   [Redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects)
-   [Headers](https://nextjs.org/docs/api-reference/next.config.js/headers)
-   [Middleware](https://nextjs.org/docs/middleware)
-   [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration)
-   [`getStaticPaths` with `fallback: true`](https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-true)
-   [`getStaticPaths` with `fallback: 'blocking'`](https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-blocking)
-   [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)

### [`getInitialProps`](https://nextjs.org/docs/advanced-features/static-html-export#getinitialprops)

It's possible to use the [`getInitialProps`](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props) API instead of `getStaticProps`, but it comes with a few caveats:

-   `getInitialProps` cannot be used alongside `getStaticProps` or `getStaticPaths` on any given page. If you have dynamic routes, instead of using `getStaticPaths` you'll need to configure the [`exportPathMap`](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap) parameter in your [`next.config.js`](https://nextjs.org/docs/api-reference/next.config.js/introduction) file to let the exporter know which HTML files it should output.
-   When `getInitialProps` is called during export, the `req` and `res` fields of its [`context`](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#context-object) parameter will be empty objects, since during export there is no server running.
-   `getInitialProps` **will be called on every client-side navigation**, if you'd like to only fetch data at build-time, switch to `getStaticProps`.
-   `getInitialProps` should fetch from an API and cannot use Node.js-specific libraries or the file system like `getStaticProps` can.

We recommend migrating towards `getStaticProps` over `getInitialProps` whenever possible.

quickref taken from https://nextjs.org/docs/advanced-features/static-html-export

**Comment by jcbhmr** [comment]
- https://github.com/vercel/next.js/issues/43417
- https://github.com/vercel/next.js/issues/42282
- https://github.com/vercel/next.js/issues/44002

Turns out it's not supported to `next export` while using `app/` right now... 😭

Oh well, just have to use the regular old pages dir.

**Comment by eitsupi** [comment]
What framework do you intend to use?
I can't help you as I know very little about JS, but I believe Docusaurus for example is popular on GitHub Pages.

**Comment by jcbhmr** [comment]
I was going try to use Next.js with a dead-simple `useStaticProps()` and `useStaticPaths()` function. At least I tried to. 🤷‍♂️ Didn't get very far.

I'll look into using Docusaurus. Thanks for your recommendation! 🚀

**Comment by jcbhmr** [comment]
Closing for now because I've decided to just ditch this (but only temporarily). In an effort to get _something_ working, I've reverted back to the old README.md PR doc generation workflow.

Dear future @jcbhmr: just open a new issue when you want to revisit SSG docs
